-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity robotControl is
port (
    dutyLeft : OUT STD_LOGIC_VECTOR (15 downto 0);
    dutyRight : OUT STD_LOGIC_VECTOR (15 downto 0);
    sensors : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of robotControl is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "robotControl_robotControl,hls_ip_2023_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.922625,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=42,HLS_VERSION=2023_1}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv8_3F : STD_LOGIC_VECTOR (7 downto 0) := "00111111";
    constant ap_const_lv16_B4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010110100";
    constant ap_const_lv8_3E : STD_LOGIC_VECTOR (7 downto 0) := "00111110";
    constant ap_const_lv8_3D : STD_LOGIC_VECTOR (7 downto 0) := "00111101";
    constant ap_const_lv16_50 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001010000";
    constant ap_const_lv8_3C : STD_LOGIC_VECTOR (7 downto 0) := "00111100";
    constant ap_const_lv8_3B : STD_LOGIC_VECTOR (7 downto 0) := "00111011";
    constant ap_const_lv16_78 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001111000";
    constant ap_const_lv8_3A : STD_LOGIC_VECTOR (7 downto 0) := "00111010";
    constant ap_const_lv8_39 : STD_LOGIC_VECTOR (7 downto 0) := "00111001";
    constant ap_const_lv8_38 : STD_LOGIC_VECTOR (7 downto 0) := "00111000";
    constant ap_const_lv8_37 : STD_LOGIC_VECTOR (7 downto 0) := "00110111";
    constant ap_const_lv8_36 : STD_LOGIC_VECTOR (7 downto 0) := "00110110";
    constant ap_const_lv8_35 : STD_LOGIC_VECTOR (7 downto 0) := "00110101";
    constant ap_const_lv8_34 : STD_LOGIC_VECTOR (7 downto 0) := "00110100";
    constant ap_const_lv8_33 : STD_LOGIC_VECTOR (7 downto 0) := "00110011";
    constant ap_const_lv8_32 : STD_LOGIC_VECTOR (7 downto 0) := "00110010";
    constant ap_const_lv8_31 : STD_LOGIC_VECTOR (7 downto 0) := "00110001";
    constant ap_const_lv8_30 : STD_LOGIC_VECTOR (7 downto 0) := "00110000";
    constant ap_const_lv8_2F : STD_LOGIC_VECTOR (7 downto 0) := "00101111";
    constant ap_const_lv8_2E : STD_LOGIC_VECTOR (7 downto 0) := "00101110";
    constant ap_const_lv8_2D : STD_LOGIC_VECTOR (7 downto 0) := "00101101";
    constant ap_const_lv8_2C : STD_LOGIC_VECTOR (7 downto 0) := "00101100";
    constant ap_const_lv8_2B : STD_LOGIC_VECTOR (7 downto 0) := "00101011";
    constant ap_const_lv8_2A : STD_LOGIC_VECTOR (7 downto 0) := "00101010";
    constant ap_const_lv8_29 : STD_LOGIC_VECTOR (7 downto 0) := "00101001";
    constant ap_const_lv8_28 : STD_LOGIC_VECTOR (7 downto 0) := "00101000";
    constant ap_const_lv8_27 : STD_LOGIC_VECTOR (7 downto 0) := "00100111";
    constant ap_const_lv8_26 : STD_LOGIC_VECTOR (7 downto 0) := "00100110";
    constant ap_const_lv8_25 : STD_LOGIC_VECTOR (7 downto 0) := "00100101";
    constant ap_const_lv8_24 : STD_LOGIC_VECTOR (7 downto 0) := "00100100";
    constant ap_const_lv8_23 : STD_LOGIC_VECTOR (7 downto 0) := "00100011";
    constant ap_const_lv8_22 : STD_LOGIC_VECTOR (7 downto 0) := "00100010";
    constant ap_const_lv8_21 : STD_LOGIC_VECTOR (7 downto 0) := "00100001";
    constant ap_const_lv8_20 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_const_lv8_1F : STD_LOGIC_VECTOR (7 downto 0) := "00011111";
    constant ap_const_lv8_1E : STD_LOGIC_VECTOR (7 downto 0) := "00011110";
    constant ap_const_lv8_1D : STD_LOGIC_VECTOR (7 downto 0) := "00011101";
    constant ap_const_lv8_1C : STD_LOGIC_VECTOR (7 downto 0) := "00011100";
    constant ap_const_lv8_1B : STD_LOGIC_VECTOR (7 downto 0) := "00011011";
    constant ap_const_lv8_1A : STD_LOGIC_VECTOR (7 downto 0) := "00011010";
    constant ap_const_lv8_19 : STD_LOGIC_VECTOR (7 downto 0) := "00011001";
    constant ap_const_lv8_18 : STD_LOGIC_VECTOR (7 downto 0) := "00011000";
    constant ap_const_lv8_17 : STD_LOGIC_VECTOR (7 downto 0) := "00010111";
    constant ap_const_lv8_16 : STD_LOGIC_VECTOR (7 downto 0) := "00010110";
    constant ap_const_lv8_15 : STD_LOGIC_VECTOR (7 downto 0) := "00010101";
    constant ap_const_lv8_14 : STD_LOGIC_VECTOR (7 downto 0) := "00010100";
    constant ap_const_lv8_13 : STD_LOGIC_VECTOR (7 downto 0) := "00010011";
    constant ap_const_lv8_12 : STD_LOGIC_VECTOR (7 downto 0) := "00010010";
    constant ap_const_lv8_11 : STD_LOGIC_VECTOR (7 downto 0) := "00010001";
    constant ap_const_lv8_10 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_const_lv8_F : STD_LOGIC_VECTOR (7 downto 0) := "00001111";
    constant ap_const_lv8_E : STD_LOGIC_VECTOR (7 downto 0) := "00001110";
    constant ap_const_lv8_D : STD_LOGIC_VECTOR (7 downto 0) := "00001101";
    constant ap_const_lv8_C : STD_LOGIC_VECTOR (7 downto 0) := "00001100";
    constant ap_const_lv8_B : STD_LOGIC_VECTOR (7 downto 0) := "00001011";
    constant ap_const_lv8_A : STD_LOGIC_VECTOR (7 downto 0) := "00001010";
    constant ap_const_lv8_9 : STD_LOGIC_VECTOR (7 downto 0) := "00001001";
    constant ap_const_lv8_8 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_const_lv8_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000111";
    constant ap_const_lv8_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000110";
    constant ap_const_lv8_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000101";
    constant ap_const_lv8_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_const_lv8_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000011";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal sensors_read_read_fu_164_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin




    dutyLeft_assign_proc : process(sensors_read_read_fu_164_p2)
    begin
        if (((sensors_read_read_fu_164_p2 = ap_const_lv8_2B) or (sensors_read_read_fu_164_p2 = ap_const_lv8_2E) or (sensors_read_read_fu_164_p2 = ap_const_lv8_30) or (sensors_read_read_fu_164_p2 = ap_const_lv8_3A) or (sensors_read_read_fu_164_p2 = ap_const_lv8_0) or (sensors_read_read_fu_164_p2 = ap_const_lv8_3) or (sensors_read_read_fu_164_p2 = ap_const_lv8_8) or (sensors_read_read_fu_164_p2 = ap_const_lv8_B) or (sensors_read_read_fu_164_p2 = ap_const_lv8_D) or (sensors_read_read_fu_164_p2 = ap_const_lv8_12) or (sensors_read_read_fu_164_p2 = ap_const_lv8_14) or (sensors_read_read_fu_164_p2 = ap_const_lv8_15) or (sensors_read_read_fu_164_p2 = ap_const_lv8_17) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1A) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1B) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1D) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1E) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1F))) then 
            dutyLeft <= ap_const_lv16_78;
        elsif (((sensors_read_read_fu_164_p2 = ap_const_lv8_21) or (sensors_read_read_fu_164_p2 = ap_const_lv8_22) or (sensors_read_read_fu_164_p2 = ap_const_lv8_23) or (sensors_read_read_fu_164_p2 = ap_const_lv8_24) or (sensors_read_read_fu_164_p2 = ap_const_lv8_25) or (sensors_read_read_fu_164_p2 = ap_const_lv8_26) or (sensors_read_read_fu_164_p2 = ap_const_lv8_27) or (sensors_read_read_fu_164_p2 = ap_const_lv8_28) or (sensors_read_read_fu_164_p2 = ap_const_lv8_29) or (sensors_read_read_fu_164_p2 = ap_const_lv8_2A) or (sensors_read_read_fu_164_p2 = ap_const_lv8_2C) or (sensors_read_read_fu_164_p2 = ap_const_lv8_2D) or (sensors_read_read_fu_164_p2 = ap_const_lv8_2F) or (sensors_read_read_fu_164_p2 = ap_const_lv8_31) or (sensors_read_read_fu_164_p2 = ap_const_lv8_32) or (sensors_read_read_fu_164_p2 = ap_const_lv8_33) or (sensors_read_read_fu_164_p2 = ap_const_lv8_35) or (sensors_read_read_fu_164_p2 = ap_const_lv8_36) or (sensors_read_read_fu_164_p2 = ap_const_lv8_37) or (sensors_read_read_fu_164_p2 = ap_const_lv8_4) or (sensors_read_read_fu_164_p2 
    = ap_const_lv8_3C) or (sensors_read_read_fu_164_p2 = ap_const_lv8_10) or (sensors_read_read_fu_164_p2 = ap_const_lv8_11) or (sensors_read_read_fu_164_p2 = ap_const_lv8_13) or (sensors_read_read_fu_164_p2 = ap_const_lv8_16) or (sensors_read_read_fu_164_p2 = ap_const_lv8_18) or (sensors_read_read_fu_164_p2 = ap_const_lv8_19) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1C) or (sensors_read_read_fu_164_p2 = ap_const_lv8_20))) then 
            dutyLeft <= ap_const_lv16_50;
        elsif (((sensors_read_read_fu_164_p2 = ap_const_lv8_34) or (sensors_read_read_fu_164_p2 = ap_const_lv8_39) or (sensors_read_read_fu_164_p2 = ap_const_lv8_3B) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1) or (sensors_read_read_fu_164_p2 = ap_const_lv8_2) or (sensors_read_read_fu_164_p2 = ap_const_lv8_5) or (sensors_read_read_fu_164_p2 = ap_const_lv8_6) or (sensors_read_read_fu_164_p2 = ap_const_lv8_7) or (sensors_read_read_fu_164_p2 = ap_const_lv8_9) or (sensors_read_read_fu_164_p2 = ap_const_lv8_A) or (sensors_read_read_fu_164_p2 = ap_const_lv8_C) or (sensors_read_read_fu_164_p2 = ap_const_lv8_E) or (sensors_read_read_fu_164_p2 = ap_const_lv8_F) or (sensors_read_read_fu_164_p2 = ap_const_lv8_3E))) then 
            dutyLeft <= ap_const_lv16_B4;
        elsif (((sensors_read_read_fu_164_p2 = ap_const_lv8_3F) or (sensors_read_read_fu_164_p2 = ap_const_lv8_38) or (sensors_read_read_fu_164_p2 = ap_const_lv8_3D) or (not((sensors_read_read_fu_164_p2 = ap_const_lv8_21)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_22)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_23)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_24)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_25)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_26)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_27)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_28)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_29)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2A)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2B)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2C)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2D)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2E)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2F)) and not((sensors_read_read_fu_164_p2 
    = ap_const_lv8_30)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_31)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_32)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_33)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_34)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_35)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_36)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_37)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_38)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_39)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_3A)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_3B)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_0)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_3C)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_3)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_4)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_5)) 
    and not((sensors_read_read_fu_164_p2 = ap_const_lv8_6)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_7)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_8)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_9)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_A)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_B)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_C)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_D)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_E)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_F)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_10)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_3D)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_11)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_12)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_13)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_14)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_15)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_16)) and not((sensors_read_read_fu_164_p2 
    = ap_const_lv8_3E)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_17)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_18)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_19)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1A)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1B)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1C)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1D)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1E)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1F)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_20)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_3F))))) then 
            dutyLeft <= ap_const_lv16_0;
        else 
            dutyLeft <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dutyRight_assign_proc : process(sensors_read_read_fu_164_p2)
    begin
        if (((sensors_read_read_fu_164_p2 = ap_const_lv8_28) or (sensors_read_read_fu_164_p2 = ap_const_lv8_29) or (sensors_read_read_fu_164_p2 = ap_const_lv8_2A) or (sensors_read_read_fu_164_p2 = ap_const_lv8_2B) or (sensors_read_read_fu_164_p2 = ap_const_lv8_2C) or (sensors_read_read_fu_164_p2 = ap_const_lv8_2D) or (sensors_read_read_fu_164_p2 = ap_const_lv8_2F) or (sensors_read_read_fu_164_p2 = ap_const_lv8_30) or (sensors_read_read_fu_164_p2 = ap_const_lv8_34) or (sensors_read_read_fu_164_p2 = ap_const_lv8_39) or (sensors_read_read_fu_164_p2 = ap_const_lv8_3A) or (sensors_read_read_fu_164_p2 = ap_const_lv8_0) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1) or (sensors_read_read_fu_164_p2 = ap_const_lv8_8) or (sensors_read_read_fu_164_p2 = ap_const_lv8_9) or (sensors_read_read_fu_164_p2 = ap_const_lv8_A) or (sensors_read_read_fu_164_p2 = ap_const_lv8_B) or (sensors_read_read_fu_164_p2 = ap_const_lv8_C) or (sensors_read_read_fu_164_p2 = ap_const_lv8_D) or (sensors_read_read_fu_164_p2 = ap_const_lv8_E) or (sensors_read_read_fu_164_p2 
    = ap_const_lv8_F) or (sensors_read_read_fu_164_p2 = ap_const_lv8_10) or (sensors_read_read_fu_164_p2 = ap_const_lv8_13) or (sensors_read_read_fu_164_p2 = ap_const_lv8_14) or (sensors_read_read_fu_164_p2 = ap_const_lv8_16) or (sensors_read_read_fu_164_p2 = ap_const_lv8_19) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1A) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1B) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1D) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1E) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1F))) then 
            dutyRight <= ap_const_lv16_50;
        elsif (((sensors_read_read_fu_164_p2 = ap_const_lv8_21) or (sensors_read_read_fu_164_p2 = ap_const_lv8_22) or (sensors_read_read_fu_164_p2 = ap_const_lv8_24) or (sensors_read_read_fu_164_p2 = ap_const_lv8_26) or (sensors_read_read_fu_164_p2 = ap_const_lv8_27) or (sensors_read_read_fu_164_p2 = ap_const_lv8_31) or (sensors_read_read_fu_164_p2 = ap_const_lv8_3) or (sensors_read_read_fu_164_p2 = ap_const_lv8_4) or (sensors_read_read_fu_164_p2 = ap_const_lv8_3C) or (sensors_read_read_fu_164_p2 = ap_const_lv8_1C))) then 
            dutyRight <= ap_const_lv16_B4;
        elsif (((sensors_read_read_fu_164_p2 = ap_const_lv8_23) or (sensors_read_read_fu_164_p2 = ap_const_lv8_25) or (sensors_read_read_fu_164_p2 = ap_const_lv8_2E) or (sensors_read_read_fu_164_p2 = ap_const_lv8_32) or (sensors_read_read_fu_164_p2 = ap_const_lv8_33) or (sensors_read_read_fu_164_p2 = ap_const_lv8_35) or (sensors_read_read_fu_164_p2 = ap_const_lv8_36) or (sensors_read_read_fu_164_p2 = ap_const_lv8_37) or (sensors_read_read_fu_164_p2 = ap_const_lv8_3B) or (sensors_read_read_fu_164_p2 = ap_const_lv8_2) or (sensors_read_read_fu_164_p2 = ap_const_lv8_5) or (sensors_read_read_fu_164_p2 = ap_const_lv8_6) or (sensors_read_read_fu_164_p2 = ap_const_lv8_7) or (sensors_read_read_fu_164_p2 = ap_const_lv8_11) or (sensors_read_read_fu_164_p2 = ap_const_lv8_12) or (sensors_read_read_fu_164_p2 = ap_const_lv8_15) or (sensors_read_read_fu_164_p2 = ap_const_lv8_17) or (sensors_read_read_fu_164_p2 = ap_const_lv8_18) or (sensors_read_read_fu_164_p2 = ap_const_lv8_3E) or (sensors_read_read_fu_164_p2 = ap_const_lv8_20))) then 
            dutyRight <= ap_const_lv16_78;
        elsif (((sensors_read_read_fu_164_p2 = ap_const_lv8_3F) or (sensors_read_read_fu_164_p2 = ap_const_lv8_38) or (sensors_read_read_fu_164_p2 = ap_const_lv8_3D) or (not((sensors_read_read_fu_164_p2 = ap_const_lv8_21)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_22)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_23)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_24)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_25)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_26)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_27)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_28)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_29)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2A)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2B)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2C)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2D)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2E)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2F)) and not((sensors_read_read_fu_164_p2 
    = ap_const_lv8_30)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_31)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_32)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_33)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_34)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_35)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_36)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_37)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_38)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_39)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_3A)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_3B)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_0)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_2)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_3C)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_3)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_4)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_5)) 
    and not((sensors_read_read_fu_164_p2 = ap_const_lv8_6)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_7)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_8)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_9)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_A)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_B)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_C)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_D)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_E)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_F)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_10)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_3D)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_11)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_12)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_13)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_14)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_15)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_16)) and not((sensors_read_read_fu_164_p2 
    = ap_const_lv8_3E)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_17)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_18)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_19)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1A)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1B)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1C)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1D)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1E)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_1F)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_20)) and not((sensors_read_read_fu_164_p2 = ap_const_lv8_3F))))) then 
            dutyRight <= ap_const_lv16_0;
        else 
            dutyRight <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    sensors_read_read_fu_164_p2 <= sensors;
end behav;
