# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/hello.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PWM_0_0/design_1_PWM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_PWM_0_0 || ORIG_REF_NAME==design_1_PWM_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Mapper_0_0/design_1_Mapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Mapper_0_0 || ORIG_REF_NAME==design_1_Mapper_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Mapper_0_1/design_1_Mapper_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Mapper_0_1 || ORIG_REF_NAME==design_1_Mapper_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PWM_0_1/design_1_PWM_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_PWM_0_1 || ORIG_REF_NAME==design_1_PWM_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Mapper_0_2/design_1_Mapper_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Mapper_0_2 || ORIG_REF_NAME==design_1_Mapper_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PWM_0_2/design_1_PWM_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_PWM_0_2 || ORIG_REF_NAME==design_1_PWM_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_1 || ORIG_REF_NAME==design_1_proc_sys_reset_0_1} -quiet] -quiet

# XDC: c:/Users/au087680/Desktop/-p/gyak2/gyak2/gyak2.gen/sources_1/bd/design_1/design_1_ooc.xdc
