# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/au087680/Desktop/-p/LineFollowerHLS.xpr/LineFollowerHLS/LineFollowerSimple.srcs/sources_1/bd/robot_design/ip/robot_design_robotControl_0_0/robot_design_robotControl_0_0.xci
# IP: The module: 'robot_design_robotControl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/au087680/Desktop/-p/LineFollowerHLS.xpr/LineFollowerHLS/LineFollowerSimple.gen/sources_1/bd/robot_design/ip/robot_design_robotControl_0_0/constraints/robotControl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'robot_design_robotControl_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/au087680/Desktop/-p/LineFollowerHLS.xpr/LineFollowerHLS/LineFollowerSimple.srcs/sources_1/bd/robot_design/ip/robot_design_robotControl_0_0/robot_design_robotControl_0_0.xci
# IP: The module: 'robot_design_robotControl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/au087680/Desktop/-p/LineFollowerHLS.xpr/LineFollowerHLS/LineFollowerSimple.gen/sources_1/bd/robot_design/ip/robot_design_robotControl_0_0/constraints/robotControl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'robot_design_robotControl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
