#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Oct 13 19:55:20 CEST 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim RobotLogic_test_behav -key {Behavioral:sim_1:Functional:RobotLogic_test} -tclbatch RobotLogic_test.tcl -protoinst "protoinst_files/robot_design.protoinst" -view /home/qgeroli5/LineFollowerSimple/LineFollowerSimple.srcs/sim_1/imports/LineFollower_FIVE/Robot_test_behav.wcfg -log simulate.log"
xsim RobotLogic_test_behav -key {Behavioral:sim_1:Functional:RobotLogic_test} -tclbatch RobotLogic_test.tcl -protoinst "protoinst_files/robot_design.protoinst" -view /home/qgeroli5/LineFollowerSimple/LineFollowerSimple.srcs/sim_1/imports/LineFollower_FIVE/Robot_test_behav.wcfg -log simulate.log

