# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/robot.xdc

# Block Designs: bd/robot_design/robot_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==robot_design || ORIG_REF_NAME==robot_design} -quiet] -quiet

# IP: bd/robot_design/ip/robot_design_Clock_divider_0_0/robot_design_Clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==robot_design_Clock_divider_0_0 || ORIG_REF_NAME==robot_design_Clock_divider_0_0} -quiet] -quiet

# IP: bd/robot_design/ip/robot_design_rst_vip_0_0/robot_design_rst_vip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==robot_design_rst_vip_0_0 || ORIG_REF_NAME==robot_design_rst_vip_0_0} -quiet] -quiet

# IP: bd/robot_design/ip/robot_design_PWM_0_0/robot_design_PWM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==robot_design_PWM_0_0 || ORIG_REF_NAME==robot_design_PWM_0_0} -quiet] -quiet

# IP: bd/robot_design/ip/robot_design_PWM_1_0/robot_design_PWM_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==robot_design_PWM_1_0 || ORIG_REF_NAME==robot_design_PWM_1_0} -quiet] -quiet

# IP: bd/robot_design/ip/robot_design_clk_wiz_0/robot_design_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==robot_design_clk_wiz_0 || ORIG_REF_NAME==robot_design_clk_wiz_0} -quiet] -quiet

# IP: bd/robot_design/ip/robot_design_robotControl_0_0/robot_design_robotControl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==robot_design_robotControl_0_0 || ORIG_REF_NAME==robot_design_robotControl_0_0} -quiet] -quiet

# XDC: c:/Users/au087680/Desktop/-p/LineFollowerHLS.xpr/LineFollowerHLS/LineFollowerSimple.gen/sources_1/bd/robot_design/robot_design_ooc.xdc
