set_property IOSTANDARD LVCMOS33 [get_ports pwm_0]
set_property PACKAGE_PIN K1 [get_ports pwm_0]
set_property PACKAGE_PIN V10 [get_ports reset_0]


set_property PACKAGE_PIN F6 [get_ports pwm_2]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_2]



set_property IOSTANDARD LVCMOS33 [get_ports {Sensors[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sensors[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sensors[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Sensors[0]}]
set_property PACKAGE_PIN E7 [get_ports {Sensors[0]}]
set_property PACKAGE_PIN J4 [get_ports {Sensors[1]}]
set_property PACKAGE_PIN J3 [get_ports {Sensors[2]}]
set_property PACKAGE_PIN R17 [get_ports {Sensors[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports main_clock]
set_property IOSTANDARD LVCMOS33 [get_ports slow_clock]
set_property PACKAGE_PIN U8 [get_ports main_clock]
set_property PACKAGE_PIN T8 [get_ports slow_clock]

set_property OFFCHIP_TERM NONE [get_ports main_clock]
set_property OFFCHIP_TERM NONE [get_ports slow_clock]

set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mapped_0[0]}]
set_property PACKAGE_PIN V11 [get_ports {mapped_0[15]}]
set_property PACKAGE_PIN V12 [get_ports {mapped_0[14]}]
set_property PACKAGE_PIN V14 [get_ports {mapped_0[13]}]
set_property PACKAGE_PIN V15 [get_ports {mapped_0[12]}]
set_property PACKAGE_PIN T16 [get_ports {mapped_0[11]}]
set_property PACKAGE_PIN U14 [get_ports {mapped_0[10]}]
set_property PACKAGE_PIN T15 [get_ports {mapped_0[9]}]
set_property PACKAGE_PIN V16 [get_ports {mapped_0[8]}]
set_property PACKAGE_PIN U16 [get_ports {mapped_0[7]}]
set_property PACKAGE_PIN U17 [get_ports {mapped_0[6]}]
set_property PACKAGE_PIN V17 [get_ports {mapped_0[5]}]
set_property PACKAGE_PIN R18 [get_ports {mapped_0[4]}]
set_property PACKAGE_PIN N14 [get_ports {mapped_0[3]}]
set_property PACKAGE_PIN J13 [get_ports {mapped_0[2]}]
set_property PACKAGE_PIN K15 [get_ports {mapped_0[1]}]
set_property PACKAGE_PIN H17 [get_ports {mapped_0[0]}]
