// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="robotControl_robotControl,hls_ip_2023_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.922625,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=42,HLS_VERSION=2023_1}" *)

module robotControl (
        dutyLeft,
        dutyRight,
        sensors
);


output  [15:0] dutyLeft;
output  [15:0] dutyRight;
input  [7:0] sensors;

reg[15:0] dutyLeft;
reg[15:0] dutyRight;

wire   [7:0] sensors_read_read_fu_52_p2;
wire    ap_ce_reg;

always @ (*) begin
    if (((sensors_read_read_fu_52_p2 == 8'd1) | (sensors_read_read_fu_52_p2 == 8'd2) | (sensors_read_read_fu_52_p2 == 8'd3))) begin
        dutyLeft = 16'd180;
    end else if (((sensors_read_read_fu_52_p2 == 8'd0) | (sensors_read_read_fu_52_p2 == 8'd4))) begin
        dutyLeft = 16'd80;
    end else if ((sensors_read_read_fu_52_p2 == 8'd6)) begin
        dutyLeft = 16'd120;
    end else if (((sensors_read_read_fu_52_p2 == 8'd7) | (sensors_read_read_fu_52_p2 == 8'd5) | (~(sensors_read_read_fu_52_p2 == 8'd0) & ~(sensors_read_read_fu_52_p2 == 8'd1) & ~(sensors_read_read_fu_52_p2 == 8'd2) & ~(sensors_read_read_fu_52_p2 == 8'd3) & ~(sensors_read_read_fu_52_p2 == 8'd4) & ~(sensors_read_read_fu_52_p2 == 8'd5) & ~(sensors_read_read_fu_52_p2 == 8'd6) & ~(sensors_read_read_fu_52_p2 == 8'd7)))) begin
        dutyLeft = 16'd0;
    end else begin
        dutyLeft = 'bx;
    end
end

always @ (*) begin
    if ((sensors_read_read_fu_52_p2 == 8'd1)) begin
        dutyRight = 16'd80;
    end else if (((sensors_read_read_fu_52_p2 == 8'd0) | (sensors_read_read_fu_52_p2 == 8'd3))) begin
        dutyRight = 16'd120;
    end else if (((sensors_read_read_fu_52_p2 == 8'd2) | (sensors_read_read_fu_52_p2 == 8'd4) | (sensors_read_read_fu_52_p2 == 8'd6))) begin
        dutyRight = 16'd180;
    end else if (((sensors_read_read_fu_52_p2 == 8'd7) | (sensors_read_read_fu_52_p2 == 8'd5) | (~(sensors_read_read_fu_52_p2 == 8'd0) & ~(sensors_read_read_fu_52_p2 == 8'd1) & ~(sensors_read_read_fu_52_p2 == 8'd2) & ~(sensors_read_read_fu_52_p2 == 8'd3) & ~(sensors_read_read_fu_52_p2 == 8'd4) & ~(sensors_read_read_fu_52_p2 == 8'd5) & ~(sensors_read_read_fu_52_p2 == 8'd6) & ~(sensors_read_read_fu_52_p2 == 8'd7)))) begin
        dutyRight = 16'd0;
    end else begin
        dutyRight = 'bx;
    end
end

assign sensors_read_read_fu_52_p2 = sensors;

endmodule //robotControl
