set_property SRC_FILE_INFO {cfile:C:/Users/au087680/Desktop/-p/gyak2/gyak2/gyak2.srcs/constrs_1/new/hello.xdc rfile:../../../gyak2.srcs/constrs_1/new/hello.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports A]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports B]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R12 [get_ports C]
