// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="robotControl_robotControl,hls_ip_2023_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.922625,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=42,HLS_VERSION=2023_1}" *)

module robotControl (
        dutyLeft,
        dutyRight,
        sensors
);


output  [15:0] dutyLeft;
output  [15:0] dutyRight;
input  [7:0] sensors;

reg[15:0] dutyLeft;
reg[15:0] dutyRight;

wire   [7:0] sensors_read_read_fu_164_p2;
wire    ap_ce_reg;

always @ (*) begin
    if (((sensors_read_read_fu_164_p2 == 8'd43) | (sensors_read_read_fu_164_p2 == 8'd46) | (sensors_read_read_fu_164_p2 == 8'd48) | (sensors_read_read_fu_164_p2 == 8'd58) | (sensors_read_read_fu_164_p2 == 8'd0) | (sensors_read_read_fu_164_p2 == 8'd3) | (sensors_read_read_fu_164_p2 == 8'd8) | (sensors_read_read_fu_164_p2 == 8'd11) | (sensors_read_read_fu_164_p2 == 8'd13) | (sensors_read_read_fu_164_p2 == 8'd18) | (sensors_read_read_fu_164_p2 == 8'd20) | (sensors_read_read_fu_164_p2 == 8'd21) | (sensors_read_read_fu_164_p2 == 8'd23) | (sensors_read_read_fu_164_p2 == 8'd26) | (sensors_read_read_fu_164_p2 == 8'd27) | (sensors_read_read_fu_164_p2 == 8'd29) | (sensors_read_read_fu_164_p2 == 8'd30) | (sensors_read_read_fu_164_p2 == 8'd31))) begin
        dutyLeft = 16'd120;
    end else if (((sensors_read_read_fu_164_p2 == 8'd33) | (sensors_read_read_fu_164_p2 == 8'd34) | (sensors_read_read_fu_164_p2 == 8'd35) | (sensors_read_read_fu_164_p2 == 8'd36) | (sensors_read_read_fu_164_p2 == 8'd37) | (sensors_read_read_fu_164_p2 == 8'd38) | (sensors_read_read_fu_164_p2 == 8'd39) | (sensors_read_read_fu_164_p2 == 8'd40) | (sensors_read_read_fu_164_p2 == 8'd41) | (sensors_read_read_fu_164_p2 == 8'd42) | (sensors_read_read_fu_164_p2 == 8'd44) | (sensors_read_read_fu_164_p2 == 8'd45) | (sensors_read_read_fu_164_p2 == 8'd47) | (sensors_read_read_fu_164_p2 == 8'd49) | (sensors_read_read_fu_164_p2 == 8'd50) | (sensors_read_read_fu_164_p2 == 8'd51) | (sensors_read_read_fu_164_p2 == 8'd53) | (sensors_read_read_fu_164_p2 == 8'd54) | (sensors_read_read_fu_164_p2 == 8'd55) | (sensors_read_read_fu_164_p2 == 8'd4) | (sensors_read_read_fu_164_p2 == 8'd60) | (sensors_read_read_fu_164_p2 == 8'd16) | (sensors_read_read_fu_164_p2 == 8'd17) | (sensors_read_read_fu_164_p2 == 8'd19) | (sensors_read_read_fu_164_p2 == 8'd22) | 
    (sensors_read_read_fu_164_p2 == 8'd24) | (sensors_read_read_fu_164_p2 == 8'd25) | (sensors_read_read_fu_164_p2 == 8'd28) | (sensors_read_read_fu_164_p2 == 8'd32))) begin
        dutyLeft = 16'd80;
    end else if (((sensors_read_read_fu_164_p2 == 8'd52) | (sensors_read_read_fu_164_p2 == 8'd57) | (sensors_read_read_fu_164_p2 == 8'd59) | (sensors_read_read_fu_164_p2 == 8'd1) | (sensors_read_read_fu_164_p2 == 8'd2) | (sensors_read_read_fu_164_p2 == 8'd5) | (sensors_read_read_fu_164_p2 == 8'd6) | (sensors_read_read_fu_164_p2 == 8'd7) | (sensors_read_read_fu_164_p2 == 8'd9) | (sensors_read_read_fu_164_p2 == 8'd10) | (sensors_read_read_fu_164_p2 == 8'd12) | (sensors_read_read_fu_164_p2 == 8'd14) | (sensors_read_read_fu_164_p2 == 8'd15) | (sensors_read_read_fu_164_p2 == 8'd62))) begin
        dutyLeft = 16'd180;
    end else if (((sensors_read_read_fu_164_p2 == 8'd63) | (sensors_read_read_fu_164_p2 == 8'd56) | (sensors_read_read_fu_164_p2 == 8'd61) | (~(sensors_read_read_fu_164_p2 == 8'd33) & ~(sensors_read_read_fu_164_p2 == 8'd34) & ~(sensors_read_read_fu_164_p2 == 8'd35) & ~(sensors_read_read_fu_164_p2 == 8'd36) & ~(sensors_read_read_fu_164_p2 == 8'd37) & ~(sensors_read_read_fu_164_p2 == 8'd38) & ~(sensors_read_read_fu_164_p2 == 8'd39) & ~(sensors_read_read_fu_164_p2 == 8'd40) & ~(sensors_read_read_fu_164_p2 == 8'd41) & ~(sensors_read_read_fu_164_p2 == 8'd42) & ~(sensors_read_read_fu_164_p2 == 8'd43) & ~(sensors_read_read_fu_164_p2 == 8'd44) & ~(sensors_read_read_fu_164_p2 == 8'd45) & ~(sensors_read_read_fu_164_p2 == 8'd46) & ~(sensors_read_read_fu_164_p2 == 8'd47) & ~(sensors_read_read_fu_164_p2 == 8'd48) & ~(sensors_read_read_fu_164_p2 == 8'd49) & ~(sensors_read_read_fu_164_p2 == 8'd50) & ~(sensors_read_read_fu_164_p2 == 8'd51) & ~(sensors_read_read_fu_164_p2 == 8'd52) & ~(sensors_read_read_fu_164_p2 == 8'd53) & ~(sensors_read_read_fu_164_p2 
    == 8'd54) & ~(sensors_read_read_fu_164_p2 == 8'd55) & ~(sensors_read_read_fu_164_p2 == 8'd56) & ~(sensors_read_read_fu_164_p2 == 8'd57) & ~(sensors_read_read_fu_164_p2 == 8'd58) & ~(sensors_read_read_fu_164_p2 == 8'd59) & ~(sensors_read_read_fu_164_p2 == 8'd0) & ~(sensors_read_read_fu_164_p2 == 8'd1) & ~(sensors_read_read_fu_164_p2 == 8'd2) & ~(sensors_read_read_fu_164_p2 == 8'd60) & ~(sensors_read_read_fu_164_p2 == 8'd3) & ~(sensors_read_read_fu_164_p2 == 8'd4) & ~(sensors_read_read_fu_164_p2 == 8'd5) & ~(sensors_read_read_fu_164_p2 == 8'd6) & ~(sensors_read_read_fu_164_p2 == 8'd7) & ~(sensors_read_read_fu_164_p2 == 8'd8) & ~(sensors_read_read_fu_164_p2 == 8'd9) & ~(sensors_read_read_fu_164_p2 == 8'd10) & ~(sensors_read_read_fu_164_p2 == 8'd11) & ~(sensors_read_read_fu_164_p2 == 8'd12) & ~(sensors_read_read_fu_164_p2 == 8'd13) & ~(sensors_read_read_fu_164_p2 == 8'd14) & ~(sensors_read_read_fu_164_p2 == 8'd15) & ~(sensors_read_read_fu_164_p2 == 8'd16) & ~(sensors_read_read_fu_164_p2 == 8'd61) & ~(sensors_read_read_fu_164_p2 
    == 8'd17) & ~(sensors_read_read_fu_164_p2 == 8'd18) & ~(sensors_read_read_fu_164_p2 == 8'd19) & ~(sensors_read_read_fu_164_p2 == 8'd20) & ~(sensors_read_read_fu_164_p2 == 8'd21) & ~(sensors_read_read_fu_164_p2 == 8'd22) & ~(sensors_read_read_fu_164_p2 == 8'd62) & ~(sensors_read_read_fu_164_p2 == 8'd23) & ~(sensors_read_read_fu_164_p2 == 8'd24) & ~(sensors_read_read_fu_164_p2 == 8'd25) & ~(sensors_read_read_fu_164_p2 == 8'd26) & ~(sensors_read_read_fu_164_p2 == 8'd27) & ~(sensors_read_read_fu_164_p2 == 8'd28) & ~(sensors_read_read_fu_164_p2 == 8'd29) & ~(sensors_read_read_fu_164_p2 == 8'd30) & ~(sensors_read_read_fu_164_p2 == 8'd31) & ~(sensors_read_read_fu_164_p2 == 8'd32) & ~(sensors_read_read_fu_164_p2 == 8'd63)))) begin
        dutyLeft = 16'd0;
    end else begin
        dutyLeft = 'bx;
    end
end

always @ (*) begin
    if (((sensors_read_read_fu_164_p2 == 8'd40) | (sensors_read_read_fu_164_p2 == 8'd41) | (sensors_read_read_fu_164_p2 == 8'd42) | (sensors_read_read_fu_164_p2 == 8'd43) | (sensors_read_read_fu_164_p2 == 8'd44) | (sensors_read_read_fu_164_p2 == 8'd45) | (sensors_read_read_fu_164_p2 == 8'd47) | (sensors_read_read_fu_164_p2 == 8'd48) | (sensors_read_read_fu_164_p2 == 8'd52) | (sensors_read_read_fu_164_p2 == 8'd57) | (sensors_read_read_fu_164_p2 == 8'd58) | (sensors_read_read_fu_164_p2 == 8'd0) | (sensors_read_read_fu_164_p2 == 8'd1) | (sensors_read_read_fu_164_p2 == 8'd8) | (sensors_read_read_fu_164_p2 == 8'd9) | (sensors_read_read_fu_164_p2 == 8'd10) | (sensors_read_read_fu_164_p2 == 8'd11) | (sensors_read_read_fu_164_p2 == 8'd12) | (sensors_read_read_fu_164_p2 == 8'd13) | (sensors_read_read_fu_164_p2 == 8'd14) | (sensors_read_read_fu_164_p2 == 8'd15) | (sensors_read_read_fu_164_p2 == 8'd16) | (sensors_read_read_fu_164_p2 == 8'd19) | (sensors_read_read_fu_164_p2 == 8'd20) | (sensors_read_read_fu_164_p2 == 8'd22) | (sensors_read_read_fu_164_p2 
    == 8'd25) | (sensors_read_read_fu_164_p2 == 8'd26) | (sensors_read_read_fu_164_p2 == 8'd27) | (sensors_read_read_fu_164_p2 == 8'd29) | (sensors_read_read_fu_164_p2 == 8'd30) | (sensors_read_read_fu_164_p2 == 8'd31))) begin
        dutyRight = 16'd80;
    end else if (((sensors_read_read_fu_164_p2 == 8'd33) | (sensors_read_read_fu_164_p2 == 8'd34) | (sensors_read_read_fu_164_p2 == 8'd36) | (sensors_read_read_fu_164_p2 == 8'd38) | (sensors_read_read_fu_164_p2 == 8'd39) | (sensors_read_read_fu_164_p2 == 8'd49) | (sensors_read_read_fu_164_p2 == 8'd3) | (sensors_read_read_fu_164_p2 == 8'd4) | (sensors_read_read_fu_164_p2 == 8'd60) | (sensors_read_read_fu_164_p2 == 8'd28))) begin
        dutyRight = 16'd180;
    end else if (((sensors_read_read_fu_164_p2 == 8'd35) | (sensors_read_read_fu_164_p2 == 8'd37) | (sensors_read_read_fu_164_p2 == 8'd46) | (sensors_read_read_fu_164_p2 == 8'd50) | (sensors_read_read_fu_164_p2 == 8'd51) | (sensors_read_read_fu_164_p2 == 8'd53) | (sensors_read_read_fu_164_p2 == 8'd54) | (sensors_read_read_fu_164_p2 == 8'd55) | (sensors_read_read_fu_164_p2 == 8'd59) | (sensors_read_read_fu_164_p2 == 8'd2) | (sensors_read_read_fu_164_p2 == 8'd5) | (sensors_read_read_fu_164_p2 == 8'd6) | (sensors_read_read_fu_164_p2 == 8'd7) | (sensors_read_read_fu_164_p2 == 8'd17) | (sensors_read_read_fu_164_p2 == 8'd18) | (sensors_read_read_fu_164_p2 == 8'd21) | (sensors_read_read_fu_164_p2 == 8'd23) | (sensors_read_read_fu_164_p2 == 8'd24) | (sensors_read_read_fu_164_p2 == 8'd62) | (sensors_read_read_fu_164_p2 == 8'd32))) begin
        dutyRight = 16'd120;
    end else if (((sensors_read_read_fu_164_p2 == 8'd63) | (sensors_read_read_fu_164_p2 == 8'd56) | (sensors_read_read_fu_164_p2 == 8'd61) | (~(sensors_read_read_fu_164_p2 == 8'd33) & ~(sensors_read_read_fu_164_p2 == 8'd34) & ~(sensors_read_read_fu_164_p2 == 8'd35) & ~(sensors_read_read_fu_164_p2 == 8'd36) & ~(sensors_read_read_fu_164_p2 == 8'd37) & ~(sensors_read_read_fu_164_p2 == 8'd38) & ~(sensors_read_read_fu_164_p2 == 8'd39) & ~(sensors_read_read_fu_164_p2 == 8'd40) & ~(sensors_read_read_fu_164_p2 == 8'd41) & ~(sensors_read_read_fu_164_p2 == 8'd42) & ~(sensors_read_read_fu_164_p2 == 8'd43) & ~(sensors_read_read_fu_164_p2 == 8'd44) & ~(sensors_read_read_fu_164_p2 == 8'd45) & ~(sensors_read_read_fu_164_p2 == 8'd46) & ~(sensors_read_read_fu_164_p2 == 8'd47) & ~(sensors_read_read_fu_164_p2 == 8'd48) & ~(sensors_read_read_fu_164_p2 == 8'd49) & ~(sensors_read_read_fu_164_p2 == 8'd50) & ~(sensors_read_read_fu_164_p2 == 8'd51) & ~(sensors_read_read_fu_164_p2 == 8'd52) & ~(sensors_read_read_fu_164_p2 == 8'd53) & ~(sensors_read_read_fu_164_p2 
    == 8'd54) & ~(sensors_read_read_fu_164_p2 == 8'd55) & ~(sensors_read_read_fu_164_p2 == 8'd56) & ~(sensors_read_read_fu_164_p2 == 8'd57) & ~(sensors_read_read_fu_164_p2 == 8'd58) & ~(sensors_read_read_fu_164_p2 == 8'd59) & ~(sensors_read_read_fu_164_p2 == 8'd0) & ~(sensors_read_read_fu_164_p2 == 8'd1) & ~(sensors_read_read_fu_164_p2 == 8'd2) & ~(sensors_read_read_fu_164_p2 == 8'd60) & ~(sensors_read_read_fu_164_p2 == 8'd3) & ~(sensors_read_read_fu_164_p2 == 8'd4) & ~(sensors_read_read_fu_164_p2 == 8'd5) & ~(sensors_read_read_fu_164_p2 == 8'd6) & ~(sensors_read_read_fu_164_p2 == 8'd7) & ~(sensors_read_read_fu_164_p2 == 8'd8) & ~(sensors_read_read_fu_164_p2 == 8'd9) & ~(sensors_read_read_fu_164_p2 == 8'd10) & ~(sensors_read_read_fu_164_p2 == 8'd11) & ~(sensors_read_read_fu_164_p2 == 8'd12) & ~(sensors_read_read_fu_164_p2 == 8'd13) & ~(sensors_read_read_fu_164_p2 == 8'd14) & ~(sensors_read_read_fu_164_p2 == 8'd15) & ~(sensors_read_read_fu_164_p2 == 8'd16) & ~(sensors_read_read_fu_164_p2 == 8'd61) & ~(sensors_read_read_fu_164_p2 
    == 8'd17) & ~(sensors_read_read_fu_164_p2 == 8'd18) & ~(sensors_read_read_fu_164_p2 == 8'd19) & ~(sensors_read_read_fu_164_p2 == 8'd20) & ~(sensors_read_read_fu_164_p2 == 8'd21) & ~(sensors_read_read_fu_164_p2 == 8'd22) & ~(sensors_read_read_fu_164_p2 == 8'd62) & ~(sensors_read_read_fu_164_p2 == 8'd23) & ~(sensors_read_read_fu_164_p2 == 8'd24) & ~(sensors_read_read_fu_164_p2 == 8'd25) & ~(sensors_read_read_fu_164_p2 == 8'd26) & ~(sensors_read_read_fu_164_p2 == 8'd27) & ~(sensors_read_read_fu_164_p2 == 8'd28) & ~(sensors_read_read_fu_164_p2 == 8'd29) & ~(sensors_read_read_fu_164_p2 == 8'd30) & ~(sensors_read_read_fu_164_p2 == 8'd31) & ~(sensors_read_read_fu_164_p2 == 8'd32) & ~(sensors_read_read_fu_164_p2 == 8'd63)))) begin
        dutyRight = 16'd0;
    end else begin
        dutyRight = 'bx;
    end
end

assign sensors_read_read_fu_164_p2 = sensors;

endmodule //robotControl
